name: Publish Package

on:
  push:
    branches:
      - main  # Trigger only on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Latest version

    - name: Set up Python
      uses: actions/setup-python@v4  # Latest version
      with:
        python-version: '3.10'  # Adjust to your preferred Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine

    - name: Build the package
      run: |
        python setup.py sdist bdist_wheel

    - name: Publish to PyPI
      env:
        PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      run: |
        twine upload dist/*
